// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: dataIndexGen.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------InternalData--------
type EmojiData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmojiDescription string `protobuf:"bytes,1,opt,name=emoji_description,json=emojiDescription,proto3" json:"emoji_description,omitempty"`
	EmojiUnicode     string `protobuf:"bytes,2,opt,name=emoji_unicode,json=emojiUnicode,proto3" json:"emoji_unicode,omitempty"`
}

func (x *EmojiData) Reset() {
	*x = EmojiData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataIndexGen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmojiData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmojiData) ProtoMessage() {}

func (x *EmojiData) ProtoReflect() protoreflect.Message {
	mi := &file_dataIndexGen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmojiData.ProtoReflect.Descriptor instead.
func (*EmojiData) Descriptor() ([]byte, []int) {
	return file_dataIndexGen_proto_rawDescGZIP(), []int{0}
}

func (x *EmojiData) GetEmojiDescription() string {
	if x != nil {
		return x.EmojiDescription
	}
	return ""
}

func (x *EmojiData) GetEmojiUnicode() string {
	if x != nil {
		return x.EmojiUnicode
	}
	return ""
}

// --------------SystemData--------
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionDescription string `protobuf:"bytes,1,opt,name=action_description,json=actionDescription,proto3" json:"action_description,omitempty"`
	Duration          int32  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	StartTime         uint64 `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           uint64 `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataIndexGen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_dataIndexGen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_dataIndexGen_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetActionDescription() string {
	if x != nil {
		return x.ActionDescription
	}
	return ""
}

func (x *Action) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Action) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Action) GetEndTime() uint64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ActionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionList []*Action `protobuf:"bytes,1,rep,name=action_list,json=actionList,proto3" json:"action_list,omitempty"`
}

func (x *ActionList) Reset() {
	*x = ActionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataIndexGen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionList) ProtoMessage() {}

func (x *ActionList) ProtoReflect() protoreflect.Message {
	mi := &file_dataIndexGen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionList.ProtoReflect.Descriptor instead.
func (*ActionList) Descriptor() ([]byte, []int) {
	return file_dataIndexGen_proto_rawDescGZIP(), []int{2}
}

func (x *ActionList) GetActionList() []*Action {
	if x != nil {
		return x.ActionList
	}
	return nil
}

// --------------ExternalData--------
type ParsedAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmojiList *EmojiData `protobuf:"bytes,1,opt,name=emoji_list,json=emojiList,proto3" json:"emoji_list,omitempty"`
}

func (x *ParsedAction) Reset() {
	*x = ParsedAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataIndexGen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParsedAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAction) ProtoMessage() {}

func (x *ParsedAction) ProtoReflect() protoreflect.Message {
	mi := &file_dataIndexGen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAction.ProtoReflect.Descriptor instead.
func (*ParsedAction) Descriptor() ([]byte, []int) {
	return file_dataIndexGen_proto_rawDescGZIP(), []int{3}
}

func (x *ParsedAction) GetEmojiList() *EmojiData {
	if x != nil {
		return x.EmojiList
	}
	return nil
}

var File_dataIndexGen_proto protoreflect.FileDescriptor

var file_dataIndexGen_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x47, 0x65, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x5d, 0x0a, 0x09, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x11,
	0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x6f,
	0x6a, 0x69, 0x5f, 0x75, 0x6e, 0x69, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x55, 0x6e, 0x69, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x8d,
	0x01, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x40,
	0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0b,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x43, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x33, 0x0a, 0x0a, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x65, 0x6d, 0x6f, 0x6a,
	0x69, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dataIndexGen_proto_rawDescOnce sync.Once
	file_dataIndexGen_proto_rawDescData = file_dataIndexGen_proto_rawDesc
)

func file_dataIndexGen_proto_rawDescGZIP() []byte {
	file_dataIndexGen_proto_rawDescOnce.Do(func() {
		file_dataIndexGen_proto_rawDescData = protoimpl.X.CompressGZIP(file_dataIndexGen_proto_rawDescData)
	})
	return file_dataIndexGen_proto_rawDescData
}

var file_dataIndexGen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dataIndexGen_proto_goTypes = []interface{}{
	(*EmojiData)(nil),    // 0: protoData.EmojiData
	(*Action)(nil),       // 1: protoData.Action
	(*ActionList)(nil),   // 2: protoData.ActionList
	(*ParsedAction)(nil), // 3: protoData.ParsedAction
}
var file_dataIndexGen_proto_depIdxs = []int32{
	1, // 0: protoData.ActionList.action_list:type_name -> protoData.Action
	0, // 1: protoData.ParsedAction.emoji_list:type_name -> protoData.EmojiData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dataIndexGen_proto_init() }
func file_dataIndexGen_proto_init() {
	if File_dataIndexGen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dataIndexGen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmojiData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataIndexGen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataIndexGen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataIndexGen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParsedAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dataIndexGen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dataIndexGen_proto_goTypes,
		DependencyIndexes: file_dataIndexGen_proto_depIdxs,
		MessageInfos:      file_dataIndexGen_proto_msgTypes,
	}.Build()
	File_dataIndexGen_proto = out.File
	file_dataIndexGen_proto_rawDesc = nil
	file_dataIndexGen_proto_goTypes = nil
	file_dataIndexGen_proto_depIdxs = nil
}
