// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: pythonServicer.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MainServicerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId uint64    `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` //define service type
	Data      *NodeData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MainServicerRequest) Reset() {
	*x = MainServicerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pythonServicer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MainServicerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainServicerRequest) ProtoMessage() {}

func (x *MainServicerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pythonServicer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainServicerRequest.ProtoReflect.Descriptor instead.
func (*MainServicerRequest) Descriptor() ([]byte, []int) {
	return file_pythonServicer_proto_rawDescGZIP(), []int{0}
}

func (x *MainServicerRequest) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MainServicerRequest) GetData() *NodeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubordinateServicerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId uint64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` //define service type
	DataType  uint64 `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	RqstData  []byte `protobuf:"bytes,3,opt,name=rqst_data,json=rqstData,proto3" json:"rqst_data,omitempty"`
}

func (x *SubordinateServicerRequest) Reset() {
	*x = SubordinateServicerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pythonServicer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubordinateServicerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubordinateServicerRequest) ProtoMessage() {}

func (x *SubordinateServicerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pythonServicer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubordinateServicerRequest.ProtoReflect.Descriptor instead.
func (*SubordinateServicerRequest) Descriptor() ([]byte, []int) {
	return file_pythonServicer_proto_rawDescGZIP(), []int{1}
}

func (x *SubordinateServicerRequest) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SubordinateServicerRequest) GetDataType() uint64 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *SubordinateServicerRequest) GetRqstData() []byte {
	if x != nil {
		return x.RqstData
	}
	return nil
}

type ServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId uint64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` //define service type
	ResData   []byte `protobuf:"bytes,2,opt,name=res_data,json=resData,proto3" json:"res_data,omitempty"`
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pythonServicer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pythonServicer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_pythonServicer_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceResponse) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ServiceResponse) GetResData() []byte {
	if x != nil {
		return x.ResData
	}
	return nil
}

// Custom Services does not have prompts
// so currently NodeData for custom services is empty
type RequestPrompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromptSentence string `protobuf:"bytes,1,opt,name=prompt_sentence,json=promptSentence,proto3" json:"prompt_sentence,omitempty"`
}

func (x *RequestPrompt) Reset() {
	*x = RequestPrompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pythonServicer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPrompt) ProtoMessage() {}

func (x *RequestPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_pythonServicer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPrompt.ProtoReflect.Descriptor instead.
func (*RequestPrompt) Descriptor() ([]byte, []int) {
	return file_pythonServicer_proto_rawDescGZIP(), []int{3}
}

func (x *RequestPrompt) GetPromptSentence() string {
	if x != nil {
		return x.PromptSentence
	}
	return ""
}

type RequestList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RequestList) Reset() {
	*x = RequestList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pythonServicer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestList) ProtoMessage() {}

func (x *RequestList) ProtoReflect() protoreflect.Message {
	mi := &file_pythonServicer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestList.ProtoReflect.Descriptor instead.
func (*RequestList) Descriptor() ([]byte, []int) {
	return file_pythonServicer_proto_rawDescGZIP(), []int{4}
}

func (x *RequestList) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type WordList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []*WordVec `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *WordList) Reset() {
	*x = WordList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pythonServicer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordList) ProtoMessage() {}

func (x *WordList) ProtoReflect() protoreflect.Message {
	mi := &file_pythonServicer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordList.ProtoReflect.Descriptor instead.
func (*WordList) Descriptor() ([]byte, []int) {
	return file_pythonServicer_proto_rawDescGZIP(), []int{5}
}

func (x *WordList) GetWords() []*WordVec {
	if x != nil {
		return x.Words
	}
	return nil
}

type WordVec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word      string    `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Dimension int32     `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Vec       []float32 `protobuf:"fixed32,3,rep,packed,name=vec,proto3" json:"vec,omitempty"`
}

func (x *WordVec) Reset() {
	*x = WordVec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pythonServicer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordVec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordVec) ProtoMessage() {}

func (x *WordVec) ProtoReflect() protoreflect.Message {
	mi := &file_pythonServicer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordVec.ProtoReflect.Descriptor instead.
func (*WordVec) Descriptor() ([]byte, []int) {
	return file_pythonServicer_proto_rawDescGZIP(), []int{6}
}

func (x *WordVec) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordVec) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *WordVec) GetVec() []float32 {
	if x != nil {
		return x.Vec
	}
	return nil
}

type SentenceVec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sentence  string    `protobuf:"bytes,1,opt,name=sentence,proto3" json:"sentence,omitempty"`
	Dimension int32     `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Vec       []float32 `protobuf:"fixed32,3,rep,packed,name=vec,proto3" json:"vec,omitempty"`
}

func (x *SentenceVec) Reset() {
	*x = SentenceVec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pythonServicer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentenceVec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentenceVec) ProtoMessage() {}

func (x *SentenceVec) ProtoReflect() protoreflect.Message {
	mi := &file_pythonServicer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentenceVec.ProtoReflect.Descriptor instead.
func (*SentenceVec) Descriptor() ([]byte, []int) {
	return file_pythonServicer_proto_rawDescGZIP(), []int{7}
}

func (x *SentenceVec) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

func (x *SentenceVec) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *SentenceVec) GetVec() []float32 {
	if x != nil {
		return x.Vec
	}
	return nil
}

var File_pythonServicer_proto protoreflect.FileDescriptor

var file_pythonServicer_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x10, 0x41, 0x50, 0x4d, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x13, 0x4d, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x75, 0x0a, 0x1a, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x71, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x72, 0x71, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a, 0x0f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0x38, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x5f, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x21, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x56,
	0x65, 0x63, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x4d, 0x0a, 0x07, 0x57, 0x6f, 0x72,
	0x64, 0x56, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x6d, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x69, 0x6d,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x65, 0x63, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x02, 0x52, 0x03, 0x76, 0x65, 0x63, 0x22, 0x59, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x74,
	0x65, 0x6e, 0x63, 0x65, 0x56, 0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x65, 0x63, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x03,
	0x76, 0x65, 0x63, 0x32, 0xbe, 0x01, 0x0a, 0x0a, 0x41, 0x50, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x50, 0x0a, 0x12, 0x4d, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x19, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x75,
	0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa2, 0x02, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a,
	0x13, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x75, 0x6e, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x1a, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x11, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x53,
	0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x56, 0x65, 0x63, 0x12, 0x3c, 0x0a, 0x0d, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x57, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0e, 0x45, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x57, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pythonServicer_proto_rawDescOnce sync.Once
	file_pythonServicer_proto_rawDescData = file_pythonServicer_proto_rawDesc
)

func file_pythonServicer_proto_rawDescGZIP() []byte {
	file_pythonServicer_proto_rawDescOnce.Do(func() {
		file_pythonServicer_proto_rawDescData = protoimpl.X.CompressGZIP(file_pythonServicer_proto_rawDescData)
	})
	return file_pythonServicer_proto_rawDescData
}

var file_pythonServicer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pythonServicer_proto_goTypes = []interface{}{
	(*MainServicerRequest)(nil),        // 0: protoData.MainServicerRequest
	(*SubordinateServicerRequest)(nil), // 1: protoData.SubordinateServicerRequest
	(*ServiceResponse)(nil),            // 2: protoData.ServiceResponse
	(*RequestPrompt)(nil),              // 3: protoData.RequestPrompt
	(*RequestList)(nil),                // 4: protoData.RequestList
	(*WordList)(nil),                   // 5: protoData.WordList
	(*WordVec)(nil),                    // 6: protoData.WordVec
	(*SentenceVec)(nil),                // 7: protoData.SentenceVec
	(*NodeData)(nil),                   // 8: protoData.NodeData
}
var file_pythonServicer_proto_depIdxs = []int32{
	8, // 0: protoData.MainServicerRequest.data:type_name -> protoData.NodeData
	6, // 1: protoData.WordList.words:type_name -> protoData.WordVec
	0, // 2: protoData.APMService.MainServiceRequest:input_type -> protoData.MainServicerRequest
	1, // 3: protoData.APMService.SubordinateServiceRequest:input_type -> protoData.SubordinateServicerRequest
	3, // 4: protoData.SubFunctionalService.EmbeddingNounChunks:input_type -> protoData.RequestPrompt
	3, // 5: protoData.SubFunctionalService.EmbeddingSentence:input_type -> protoData.RequestPrompt
	4, // 6: protoData.SubFunctionalService.EmbeddingList:input_type -> protoData.RequestList
	3, // 7: protoData.SubFunctionalService.EmbeddingTopic:input_type -> protoData.RequestPrompt
	2, // 8: protoData.APMService.MainServiceRequest:output_type -> protoData.ServiceResponse
	2, // 9: protoData.APMService.SubordinateServiceRequest:output_type -> protoData.ServiceResponse
	5, // 10: protoData.SubFunctionalService.EmbeddingNounChunks:output_type -> protoData.WordList
	7, // 11: protoData.SubFunctionalService.EmbeddingSentence:output_type -> protoData.SentenceVec
	5, // 12: protoData.SubFunctionalService.EmbeddingList:output_type -> protoData.WordList
	5, // 13: protoData.SubFunctionalService.EmbeddingTopic:output_type -> protoData.WordList
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pythonServicer_proto_init() }
func file_pythonServicer_proto_init() {
	if File_pythonServicer_proto != nil {
		return
	}
	file_APMFactory_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pythonServicer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MainServicerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pythonServicer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubordinateServicerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pythonServicer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pythonServicer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPrompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pythonServicer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pythonServicer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pythonServicer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordVec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pythonServicer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SentenceVec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pythonServicer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pythonServicer_proto_goTypes,
		DependencyIndexes: file_pythonServicer_proto_depIdxs,
		MessageInfos:      file_pythonServicer_proto_msgTypes,
	}.Build()
	File_pythonServicer_proto = out.File
	file_pythonServicer_proto_rawDesc = nil
	file_pythonServicer_proto_goTypes = nil
	file_pythonServicer_proto_depIdxs = nil
}
