# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyFunctionDistribute.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dataIndexGen_pb2 as dataIndexGen__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apyFunctionDistribute.proto\x12\tprotoData\x1a\x12\x64\x61taIndexGen.proto\"P\n\x10GeneralPyRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x1a\n\rsystem_prompt\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_system_prompt\"[\n\rTextPyRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x1a\n\rsystem_prompt\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_system_prompt2\xa2\x01\n\x13\x41PMFunctionsService\x12L\n\x1cInsertActionsWithObservation\x12\x18.protoData.TextPyRequest\x1a\x12.protoData.Actions\x12=\n\x0f\x41\x63tionFormatter\x12\x11.protoData.Action\x1a\x17.protoData.ParsedActionB\x0eZ\x0cmessage/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyFunctionDistribute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014message/grpc'
  _globals['_GENERALPYREQUEST']._serialized_start=61
  _globals['_GENERALPYREQUEST']._serialized_end=141
  _globals['_TEXTPYREQUEST']._serialized_start=143
  _globals['_TEXTPYREQUEST']._serialized_end=234
  _globals['_APMFUNCTIONSSERVICE']._serialized_start=237
  _globals['_APMFUNCTIONSSERVICE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
