# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dataIndexGen_pb2 as dataIndexGen__pb2
import pyFunctionDistribute_pb2 as pyFunctionDistribute__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pyFunctionDistribute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class APMFunctionsServiceStub(object):
    """Internal Python Service to distribute the apm request to individual functions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertActionsWithObservation = channel.unary_unary(
                '/protoData.APMFunctionsService/InsertActionsWithObservation',
                request_serializer=pyFunctionDistribute__pb2.TextPyRequest.SerializeToString,
                response_deserializer=dataIndexGen__pb2.Actions.FromString,
                _registered_method=True)
        self.ActionFormatter = channel.unary_unary(
                '/protoData.APMFunctionsService/ActionFormatter',
                request_serializer=dataIndexGen__pb2.Action.SerializeToString,
                response_deserializer=dataIndexGen__pb2.ParsedAction.FromString,
                _registered_method=True)


class APMFunctionsServiceServicer(object):
    """Internal Python Service to distribute the apm request to individual functions
    """

    def InsertActionsWithObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActionFormatter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APMFunctionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertActionsWithObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertActionsWithObservation,
                    request_deserializer=pyFunctionDistribute__pb2.TextPyRequest.FromString,
                    response_serializer=dataIndexGen__pb2.Actions.SerializeToString,
            ),
            'ActionFormatter': grpc.unary_unary_rpc_method_handler(
                    servicer.ActionFormatter,
                    request_deserializer=dataIndexGen__pb2.Action.FromString,
                    response_serializer=dataIndexGen__pb2.ParsedAction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protoData.APMFunctionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protoData.APMFunctionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class APMFunctionsService(object):
    """Internal Python Service to distribute the apm request to individual functions
    """

    @staticmethod
    def InsertActionsWithObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protoData.APMFunctionsService/InsertActionsWithObservation',
            pyFunctionDistribute__pb2.TextPyRequest.SerializeToString,
            dataIndexGen__pb2.Actions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActionFormatter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protoData.APMFunctionsService/ActionFormatter',
            dataIndexGen__pb2.Action.SerializeToString,
            dataIndexGen__pb2.ParsedAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
