// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: message/proto/APMFactory.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Every Node will take up to 5 input nodes and will have 1 output node
type NodeConnector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputNodes map[int32]*NodeData `protobuf:"bytes,1,rep,name=input_nodes,json=inputNodes,proto3" json:"input_nodes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *NodeConnector) Reset() {
	*x = NodeConnector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_APMFactory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeConnector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConnector) ProtoMessage() {}

func (x *NodeConnector) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_APMFactory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConnector.ProtoReflect.Descriptor instead.
func (*NodeConnector) Descriptor() ([]byte, []int) {
	return file_message_proto_APMFactory_proto_rawDescGZIP(), []int{0}
}

func (x *NodeConnector) GetInputNodes() map[int32]*NodeData {
	if x != nil {
		return x.InputNodes
	}
	return nil
}

type NodeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId uint64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Function NodeData Contains byte form of ServiceFunction
	// NodeData Are Only used:
	// Game Server --> mutate prompts
	//
	//	Add Raw data which does not need to be processed into input_data_obj
	//
	// Python --> unpack all node data to utilize LLM
	// Data NodeData Holds dataInformation which Game Server Does not have
	// eg. predefined MBTI Score -->MBTI Nodes
	FunctionParam *FunctionParams `protobuf:"bytes,2,opt,name=function_param,json=functionParam,proto3,oneof" json:"function_param,omitempty"`
	NodeStructure *NodeConnector  `protobuf:"bytes,3,opt,name=node_structure,json=nodeStructure,proto3,oneof" json:"node_structure,omitempty"`
}

func (x *NodeData) Reset() {
	*x = NodeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_APMFactory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeData) ProtoMessage() {}

func (x *NodeData) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_APMFactory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeData.ProtoReflect.Descriptor instead.
func (*NodeData) Descriptor() ([]byte, []int) {
	return file_message_proto_APMFactory_proto_rawDescGZIP(), []int{1}
}

func (x *NodeData) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeData) GetFunctionParam() *FunctionParams {
	if x != nil {
		return x.FunctionParam
	}
	return nil
}

func (x *NodeData) GetNodeStructure() *NodeConnector {
	if x != nil {
		return x.NodeStructure
	}
	return nil
}

type FileTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TreeType  int32     `protobuf:"varint,1,opt,name=tree_type,json=treeType,proto3" json:"tree_type,omitempty"`    // refers to FunctionIndexGen.yaml, id of blueprint base framework
	RootNode  *NodeData `protobuf:"bytes,2,opt,name=root_node,json=rootNode,proto3" json:"root_node,omitempty"`     // root node deserialize with APMFactory Node Data
	IsDefault bool      `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"` // Is using current tree as default tree
}

func (x *FileTree) Reset() {
	*x = FileTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_APMFactory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTree) ProtoMessage() {}

func (x *FileTree) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_APMFactory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTree.ProtoReflect.Descriptor instead.
func (*FileTree) Descriptor() ([]byte, []int) {
	return file_message_proto_APMFactory_proto_rawDescGZIP(), []int{2}
}

func (x *FileTree) GetTreeType() int32 {
	if x != nil {
		return x.TreeType
	}
	return 0
}

func (x *FileTree) GetRootNode() *NodeData {
	if x != nil {
		return x.RootNode
	}
	return nil
}

func (x *FileTree) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type ApmFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trees       []*FileTree `protobuf:"bytes,1,rep,name=trees,proto3" json:"trees,omitempty"` //root node is the ending node of a single service
	UsrId       int32       `protobuf:"varint,2,opt,name=usr_id,json=usrId,proto3" json:"usr_id,omitempty"`
	CharacterId int32       `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
}

func (x *ApmFile) Reset() {
	*x = ApmFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_APMFactory_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApmFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApmFile) ProtoMessage() {}

func (x *ApmFile) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_APMFactory_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApmFile.ProtoReflect.Descriptor instead.
func (*ApmFile) Descriptor() ([]byte, []int) {
	return file_message_proto_APMFactory_proto_rawDescGZIP(), []int{3}
}

func (x *ApmFile) GetTrees() []*FileTree {
	if x != nil {
		return x.Trees
	}
	return nil
}

func (x *ApmFile) GetUsrId() int32 {
	if x != nil {
		return x.UsrId
	}
	return 0
}

func (x *ApmFile) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

// into raw data slot in NodeData
type FunctionParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// General Main ServiceFunction
	FunctionPrompt *string `protobuf:"bytes,1,opt,name=function_prompt,json=functionPrompt,proto3,oneof" json:"function_prompt,omitempty"`
	// SubService Function
	InputDataObj []byte `protobuf:"bytes,2,opt,name=input_data_obj,json=inputDataObj,proto3,oneof" json:"input_data_obj,omitempty"`
	// Text MainService Function
	InputText *string `protobuf:"bytes,3,opt,name=input_text,json=inputText,proto3,oneof" json:"input_text,omitempty"`
	// system prompt for LLM
	SystemPrompt *string `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3,oneof" json:"system_prompt,omitempty"`
}

func (x *FunctionParams) Reset() {
	*x = FunctionParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_APMFactory_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionParams) ProtoMessage() {}

func (x *FunctionParams) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_APMFactory_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionParams.ProtoReflect.Descriptor instead.
func (*FunctionParams) Descriptor() ([]byte, []int) {
	return file_message_proto_APMFactory_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionParams) GetFunctionPrompt() string {
	if x != nil && x.FunctionPrompt != nil {
		return *x.FunctionPrompt
	}
	return ""
}

func (x *FunctionParams) GetInputDataObj() []byte {
	if x != nil {
		return x.InputDataObj
	}
	return nil
}

func (x *FunctionParams) GetInputText() string {
	if x != nil && x.InputText != nil {
		return *x.InputText
	}
	return ""
}

func (x *FunctionParams) GetSystemPrompt() string {
	if x != nil && x.SystemPrompt != nil {
		return *x.SystemPrompt
	}
	return ""
}

var File_message_proto_APMFactory_proto protoreflect.FileDescriptor

var file_message_proto_APMFactory_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x41, 0x50, 0x4d, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x22, 0xae, 0x01, 0x0a, 0x0d,
	0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x49, 0x0a,
	0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0x52, 0x0a, 0x0f, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd6, 0x01, 0x0a,
	0x08, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x12, 0x45, 0x0a, 0x0e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x44, 0x0a, 0x0e, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x01, 0x52, 0x0d, 0x6e,
	0x6f, 0x64, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x11, 0x0a, 0x0f, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x22, 0x78, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x65,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x72, 0x65, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30,
	0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22,
	0x6e, 0x0a, 0x07, 0x61, 0x70, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x74, 0x72,
	0x65, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x65, 0x65, 0x52, 0x05,
	0x74, 0x72, 0x65, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x75, 0x73, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x75, 0x73, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22,
	0xff, 0x01, 0x0a, 0x0e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x2c, 0x0a, 0x0f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x29, 0x0a, 0x0e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6f,
	0x62, 0x6a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01, 0x52, 0x0c, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x62, 0x6a, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x28, 0x0a, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0c, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x88, 0x01, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x42, 0x11, 0x0a,
	0x0f, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6f, 0x62, 0x6a,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x42,
	0x10, 0x0a, 0x0e, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_message_proto_APMFactory_proto_rawDescOnce sync.Once
	file_message_proto_APMFactory_proto_rawDescData = file_message_proto_APMFactory_proto_rawDesc
)

func file_message_proto_APMFactory_proto_rawDescGZIP() []byte {
	file_message_proto_APMFactory_proto_rawDescOnce.Do(func() {
		file_message_proto_APMFactory_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_APMFactory_proto_rawDescData)
	})
	return file_message_proto_APMFactory_proto_rawDescData
}

var file_message_proto_APMFactory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_message_proto_APMFactory_proto_goTypes = []interface{}{
	(*NodeConnector)(nil),  // 0: protoData.NodeConnector
	(*NodeData)(nil),       // 1: protoData.NodeData
	(*FileTree)(nil),       // 2: protoData.FileTree
	(*ApmFile)(nil),        // 3: protoData.apmFile
	(*FunctionParams)(nil), // 4: protoData.FunctionParams
	nil,                    // 5: protoData.NodeConnector.InputNodesEntry
}
var file_message_proto_APMFactory_proto_depIdxs = []int32{
	5, // 0: protoData.NodeConnector.input_nodes:type_name -> protoData.NodeConnector.InputNodesEntry
	4, // 1: protoData.NodeData.function_param:type_name -> protoData.FunctionParams
	0, // 2: protoData.NodeData.node_structure:type_name -> protoData.NodeConnector
	1, // 3: protoData.FileTree.root_node:type_name -> protoData.NodeData
	2, // 4: protoData.apmFile.trees:type_name -> protoData.FileTree
	1, // 5: protoData.NodeConnector.InputNodesEntry.value:type_name -> protoData.NodeData
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_message_proto_APMFactory_proto_init() }
func file_message_proto_APMFactory_proto_init() {
	if File_message_proto_APMFactory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_APMFactory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeConnector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_APMFactory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_APMFactory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_APMFactory_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApmFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_APMFactory_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_proto_APMFactory_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_message_proto_APMFactory_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_APMFactory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_APMFactory_proto_goTypes,
		DependencyIndexes: file_message_proto_APMFactory_proto_depIdxs,
		MessageInfos:      file_message_proto_APMFactory_proto_msgTypes,
	}.Build()
	File_message_proto_APMFactory_proto = out.File
	file_message_proto_APMFactory_proto_rawDesc = nil
	file_message_proto_APMFactory_proto_goTypes = nil
	file_message_proto_APMFactory_proto_depIdxs = nil
}
