# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/proto/functionDistribute.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from message.proto import dataIndexGen_pb2 as message_dot_proto_dot_dataIndexGen__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&message/proto/functionDistribute.proto\x12\tprotoData\x1a message/proto/dataIndexGen.proto\"^\n\x10GeneralPyRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x1a\n\rsystem_prompt\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_system_prompt2\xa7\x01\n\x13\x41PMFunctionsService\x12Q\n\x1bInsertActionWithObservation\x12\x1b.protoData.GeneralPyRequest\x1a\x15.protoData.ActionList\x12=\n\x0f\x41\x63tionFormatter\x12\x11.protoData.Action\x1a\x17.protoData.ParsedActionB\x17Z\x15golang-client/messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message.proto.functionDistribute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025golang-client/message'
  _globals['_GENERALPYREQUEST']._serialized_start=87
  _globals['_GENERALPYREQUEST']._serialized_end=181
  _globals['_APMFUNCTIONSSERVICE']._serialized_start=184
  _globals['_APMFUNCTIONSSERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
